import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.165.0/build/three.module.js';
const canvas=document.querySelector('#c'), renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x020504);scene.fog=new THREE.FogExp2(0x030807,.028);const cam=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.1,180);cam.position.set(0,2.1,10);
scene.add(new THREE.HemisphereLight(0x9fe4cb,0x07100d,.4));const head=new THREE.SpotLight(0xd9fff0,55,50,.6,.6,1);head.position.set(0,0,0);head.target.position.set(0,0,-3);cam.add(head,head.target);scene.add(cam);const amber=new THREE.PointLight(0xff9f45,38,24,2);amber.position.set(-6,3,-18);scene.add(amber);
function rockGeo(r=1){return new THREE.DodecahedronGeometry(r,1)}const rockMat=new THREE.MeshStandardMaterial({color:0x25332d,roughness:.82,metalness:.08,flatShading:true});const ground=new THREE.Mesh(new THREE.PlaneGeometry(160,220,20,24),rockMat);ground.rotation.x=-Math.PI/2;ground.position.y=0;let p=ground.geometry.attributes.position;for(let i=0;i<p.count;i++)p.setZ(i,(Math.random()-.5)*1.2);ground.geometry.computeVertexNormals();scene.add(ground);
for(let i=0;i<110;i++){let m=new THREE.Mesh(rockGeo(1+Math.random()*4),rockMat.clone());m.material.color.offsetHSL(0,0,(Math.random()-.5)*.08);let side=Math.random()<.5?-1:1;m.position.set(side*(7+Math.random()*16),Math.random()*7-1,-Math.random()*110+12);m.scale.set(1+Math.random()*2,1+Math.random()*2,1+Math.random()*2);m.rotation.set(Math.random()*3,Math.random()*3,Math.random()*3);scene.add(m)}
const ores=[];for(let i=0;i<22;i++){let g=new THREE.IcosahedronGeometry(.45+Math.random()*.6,1),mat=new THREE.MeshPhysicalMaterial({color:i%4?0x49a982:0x8f62d8,emissive:i%4?0x1a6b50:0x432477,emissiveIntensity:1.4,roughness:.22,metalness:.25,transmission:.1});let m=new THREE.Mesh(g,mat);m.position.set((Math.random()-.5)*12,1+Math.random()*3,-8-Math.random()*90);m.userData={ore:true,kg:.6+Math.random()*1.3,type:i%4?'COBALT GLASS':'VOID OPAL'};ores.push(m);scene.add(m);let l=new THREE.PointLight(mat.color,5,7);m.add(l)}
for(let z=-10;z>-100;z-=20){let ring=new THREE.Mesh(new THREE.TorusGeometry(7,.09,6,32),new THREE.MeshStandardMaterial({color:0x54635c,metalness:.8,roughness:.3}));ring.position.set(0,4,z);ring.scale.y=.65;scene.add(ring)}
const dust=new THREE.BufferGeometry(),a=new Float32Array(1500*3);for(let i=0;i<a.length;i+=3){a[i]=(Math.random()-.5)*35;a[i+1]=Math.random()*12;a[i+2]=-Math.random()*120+15}dust.setAttribute('position',new THREE.BufferAttribute(a,3));scene.add(new THREE.Points(dust,new THREE.PointsMaterial({color:0xb9d5c5,size:.035,transparent:true,opacity:.45})));
let yaw=0,pitch=0,started=false,keys={},ore=0,heat=0,credits=2450;const ray=new THREE.Raycaster();function toast(t){let e=document.querySelector('#toast');e.textContent=t;clearTimeout(e.t);e.t=setTimeout(()=>e.textContent='',1300)}
document.querySelector('#deploy').onclick=()=>{started=true;document.querySelector('#boot').classList.add('hide');canvas.requestPointerLock()};addEventListener('keydown',e=>{keys[e.code]=1;if(e.code==='KeyE'){document.querySelector('#scanring').classList.remove('scanning');void document.querySelector('#scanring').offsetWidth;document.querySelector('#scanring').classList.add('scanning');let near=ores.filter(o=>o.visible&&o.position.distanceTo(cam.position)<22).length;toast(`LIDAR: ${near} MINERAL SIGNATURE${near===1?'':'S'}`)}});addEventListener('keyup',e=>keys[e.code]=0);addEventListener('mousemove',e=>{if(document.pointerLockElement===canvas){yaw-=e.movementX*.0022;pitch=Math.max(-1.2,Math.min(1.2,pitch-e.movementY*.0022))}});canvas.onclick=()=>{if(started&&document.pointerLockElement!==canvas){canvas.requestPointerLock();return}if(heat>85)return toast('CUTTER OVERHEATED');ray.setFromCamera(new THREE.Vector2(),cam);let hit=ray.intersectObjects(ores.filter(o=>o.visible))[0];heat=Math.min(100,heat+18);if(hit&&hit.distance<7){let m=hit.object;m.scale.multiplyScalar(.72);m.userData.hits=(m.userData.hits||0)+1;toast('CUTTING '+m.userData.type);if(m.userData.hits>=3){m.visible=false;ore+=m.userData.kg;credits+=Math.round(m.userData.kg*180);document.querySelector('#ore').textContent=ore.toFixed(1);document.querySelector('#prog').style.width=Math.min(100,ore/12*100)+'%';document.querySelector('#credits').textContent=credits.toLocaleString();document.querySelector('#cargo').innerHTML=`<div><span>${m.userData.type}</span><b>+${m.userData.kg.toFixed(1)} KG</b></div>`;toast('EXTRACTED +'+m.userData.kg.toFixed(1)+' KG');if(ore>=12)toast('CONTRACT COMPLETE · EXTRACTION UNLOCKED')}}};
let last=performance.now();function loop(t){requestAnimationFrame(loop);let dt=Math.min(.033,(t-last)/1000);last=t;cam.rotation.set(pitch,yaw,0,'YXZ');if(started){let speed=(keys.ShiftLeft?8:4.5)*dt,fwd=new THREE.Vector3(-Math.sin(yaw),0,-Math.cos(yaw)),right=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw));if(keys.KeyW)cam.position.addScaledVector(fwd,speed);if(keys.KeyS)cam.position.addScaledVector(fwd,-speed);if(keys.KeyA)cam.position.addScaledVector(right,-speed);if(keys.KeyD)cam.position.addScaledVector(right,speed);cam.position.x=Math.max(-6,Math.min(6,cam.position.x));cam.position.z=Math.max(-104,Math.min(14,cam.position.z));cam.position.y=2.1+Math.sin(t*.002)*.035;document.querySelector('#depth').textContent=Math.round(1842-cam.position.z*2.8).toLocaleString()+'m'}heat=Math.max(0,heat-dt*12);document.querySelector('#heat').style.width=heat+'%';renderer.render(scene,cam)}loop(last);addEventListener('resize',()=>{cam.aspect=innerWidth/innerHeight;cam.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
